name: CI
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }

jobs:
  test-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest -q
      - name: Streamlit smoke test
        env:
          GOOGLE_API_KEY: dummy-key-1234567890
        run: |
          nohup streamlit run main.py --server.headless true --server.port 8501 &
          for i in {1..20}; do
            sleep 2
            if curl -sSf http://127.0.0.1:8501/ >/dev/null; then
              echo "Streamlit is up"
              exit 0
            fi
          done
          echo "Streamlit did not start in time"
          exit 1
